import React from 'react';
// import { FaSadTear } from 'react-icons/fa';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';

const Error = () => {
  return (
    <>
      <Head>
        <title>error</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./iconhead.png' />
      </Head>
      <div className='w-screen h-[700px] flex items-center justify-center text-center gap-x-32'>
        <Image
          className='animate-bounce'
          style={{ animationDuration: '3s' }}
          src={'/error.svg'}
          alt='error'
          width={400}
          height={400}
        ></Image>
        <div className='flex flex-col items-center'>
          <div>
            <h1 className='text-6xl font-bold mb-4 flex items-start'>404</h1>
            <p className='text-2xl'>
              Oops! The page you are looking for does not exist.
            </p>
          </div>
          <div className='flex justify-end py-2 w-full'>
            <Link
              href='/'
              className='p-2 border border-dashed border-gray-500 text-black rounded-lg shadow-lg transition duration-300 ease-in-out hover:bg-black hover:text-white hover:shadow-xl hover:border-dashe hover:border-white'
            >
              Back home
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Error;
