// import Image from "next/image";
import { Geist } from 'next/font/google';
import Head from 'next/head';
import Homapage from '../components/views/page';
import Navbar from '../components/views/navbar';
import Navsmile from '../components/views/navsmile';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export default function Home() {
  return (
    <div className={geistSans.variable}>
      <Head>
        <title>Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./iconhead.png' />
      </Head>
      <Navsmile
        Navbarsmall={['About', 'News', 'Events', 'Programmes', 'Help center']}
      />
      <Navbar />
      <Homapage />
    </div>
  );
}
