import { Geist } from 'next/font/google';
import Head from 'next/head';
import Singlepage from '../components/views/page';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
export default function Home() {
  return (
    <div className={`${geistSans.variable}`}>
      <Head>
        <title>Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./iconhead.png' />
      </Head>
      <Singlepage />
    </div>
  );
}
